Repository MMC-Scholars/VRBase, pull requests merged in 2020-09, with the labels that each got.

#5 Feature/unreal 4.25 update
  ABaseController/ABaseController.cpp
  ABaseController/ABaseController.h
  ABasePawn/ABasePawn.cpp
  APickup/APickup.cpp
  ASign/ASign.cpp
  AWorldButton/AWorldButton.cpp
  System/Assert.h
Labels: enhancement

#6 License Update
  ABaseController/ABaseController.h
  ABaseEntity/ABaseEntity.h
  ABaseMoving/ABaseMoving.h
  ABasePawn/ABasePawn.h
  AGameRules/AGameRules.h
  AMoveLinear/AMoveLinear.h
  APickup/APickup.h
  ASign/ASign.h
  AWorldButton/AWorldButton.h
  FMovingVector/FMovingVector.h
  IBaseEntity/IBaseEntity.h
  IBaseEntity/IBaseEntity_flags.h
  LICENSE
  LineTools/linetools.h
  System/Assert.h
  System/EHandle.h
  System/Globals.h
  System/Input.h
  System/NLogger.h
  System/VRAppSwitchFunctionLibrary.h
  System/predefs.h
  System/static_initialize.h
  System/system.h
Labels: documentation

#8 GetPickupParents() function implementation
  ABaseController/ABaseController.cpp
  APickup/APickup.cpp
  APickup/APickup.h
Labels: enhancement, help wanted
