Repository MMC-Scholars/VRBase, pull requests merged in 2020-10, with the labels that each got.

#10 SetPickupRenderCustomDepth() for static mesh component of APickup
  APickup/APickup.cpp
  APickup/APickup.h
Labels: enhancement

#11 Remove Procedural Mesh Component from Pickup
  APickup/APickup.cpp
  APickup/APickup.h
Labels: bug

#13 Add Code Formatter
  README.md
Labels: documentation

#14 Documentation Specification
  APickup/APickup.cpp
  ASign/ASign.cpp
  Doc/ABaseController.md
  Doc/ABaseEntity.md
  Doc/ABaseMoving.md
  Doc/ABasePawn.md
  Doc/AGameRules.md
  Doc/AHMDTeleportationTarget.md
  Doc/AMoveLinear.md
  Doc/APickup.md
  Doc/ASign.md
  Doc/AWorldButton.md
  Doc/ClassDiagram.svg
  Doc/Doc.md
  Doc/EHandle.md
  Doc/EntityLifecycle.svg
  Doc/FEntityInputRegistrationButtons.md
  Doc/FEntityInputRegistrationParams.md
  Doc/FPawnInstruction.md
  Doc/IBaseEntity.md
  Doc/IMovingVectorManager.md
  Doc/LineTools.md
  Doc/NLogger.md
  Doc/System.md
  Doc/globals.md
  Doc/typedefs.md
  Doc/yuml.txt
  README.md
  System/Assert.cpp
Labels: documentation
